/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtentiRouteImport } from './routes/utenti'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PreventiviRouteImport } from './routes/preventivi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListiniRouteImport } from './routes/listini'
import { Route as KitRouteImport } from './routes/kit'
import { Route as ClientiRouteImport } from './routes/clienti'
import { Route as ArticoliRouteImport } from './routes/articoli'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreventiviIdRouteImport } from './routes/preventivi.$id'
import { Route as KitIdRouteImport } from './routes/kit.$id'
import { Route as ArticoliIdRouteImport } from './routes/articoli.$id'

const UtentiRoute = UtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventiviRoute = PreventiviRouteImport.update({
  id: '/preventivi',
  path: '/preventivi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListiniRoute = ListiniRouteImport.update({
  id: '/listini',
  path: '/listini',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiRoute = ClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticoliRoute = ArticoliRouteImport.update({
  id: '/articoli',
  path: '/articoli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventiviIdRoute = PreventiviIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PreventiviRoute,
} as any)
const KitIdRoute = KitIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KitRoute,
} as any)
const ArticoliIdRoute = ArticoliIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticoliRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/clienti': typeof ClientiRoute
  '/kit': typeof KitRouteWithChildren
  '/listini': typeof ListiniRoute
  '/login': typeof LoginRoute
  '/preventivi': typeof PreventiviRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/utenti': typeof UtentiRoute
  '/articoli/$id': typeof ArticoliIdRoute
  '/kit/$id': typeof KitIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/clienti': typeof ClientiRoute
  '/kit': typeof KitRouteWithChildren
  '/listini': typeof ListiniRoute
  '/login': typeof LoginRoute
  '/preventivi': typeof PreventiviRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/utenti': typeof UtentiRoute
  '/articoli/$id': typeof ArticoliIdRoute
  '/kit/$id': typeof KitIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRouteWithChildren
  '/clienti': typeof ClientiRoute
  '/kit': typeof KitRouteWithChildren
  '/listini': typeof ListiniRoute
  '/login': typeof LoginRoute
  '/preventivi': typeof PreventiviRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/utenti': typeof UtentiRoute
  '/articoli/$id': typeof ArticoliIdRoute
  '/kit/$id': typeof KitIdRoute
  '/preventivi/$id': typeof PreventiviIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articoli'
    | '/clienti'
    | '/kit'
    | '/listini'
    | '/login'
    | '/preventivi'
    | '/reset-password'
    | '/utenti'
    | '/articoli/$id'
    | '/kit/$id'
    | '/preventivi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articoli'
    | '/clienti'
    | '/kit'
    | '/listini'
    | '/login'
    | '/preventivi'
    | '/reset-password'
    | '/utenti'
    | '/articoli/$id'
    | '/kit/$id'
    | '/preventivi/$id'
  id:
    | '__root__'
    | '/'
    | '/articoli'
    | '/clienti'
    | '/kit'
    | '/listini'
    | '/login'
    | '/preventivi'
    | '/reset-password'
    | '/utenti'
    | '/articoli/$id'
    | '/kit/$id'
    | '/preventivi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticoliRoute: typeof ArticoliRouteWithChildren
  ClientiRoute: typeof ClientiRoute
  KitRoute: typeof KitRouteWithChildren
  ListiniRoute: typeof ListiniRoute
  LoginRoute: typeof LoginRoute
  PreventiviRoute: typeof PreventiviRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UtentiRoute: typeof UtentiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utenti': {
      id: '/utenti'
      path: '/utenti'
      fullPath: '/utenti'
      preLoaderRoute: typeof UtentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivi': {
      id: '/preventivi'
      path: '/preventivi'
      fullPath: '/preventivi'
      preLoaderRoute: typeof PreventiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listini': {
      id: '/listini'
      path: '/listini'
      fullPath: '/listini'
      preLoaderRoute: typeof ListiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti': {
      id: '/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof ClientiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articoli': {
      id: '/articoli'
      path: '/articoli'
      fullPath: '/articoli'
      preLoaderRoute: typeof ArticoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivi/$id': {
      id: '/preventivi/$id'
      path: '/$id'
      fullPath: '/preventivi/$id'
      preLoaderRoute: typeof PreventiviIdRouteImport
      parentRoute: typeof PreventiviRoute
    }
    '/kit/$id': {
      id: '/kit/$id'
      path: '/$id'
      fullPath: '/kit/$id'
      preLoaderRoute: typeof KitIdRouteImport
      parentRoute: typeof KitRoute
    }
    '/articoli/$id': {
      id: '/articoli/$id'
      path: '/$id'
      fullPath: '/articoli/$id'
      preLoaderRoute: typeof ArticoliIdRouteImport
      parentRoute: typeof ArticoliRoute
    }
  }
}

interface ArticoliRouteChildren {
  ArticoliIdRoute: typeof ArticoliIdRoute
}

const ArticoliRouteChildren: ArticoliRouteChildren = {
  ArticoliIdRoute: ArticoliIdRoute,
}

const ArticoliRouteWithChildren = ArticoliRoute._addFileChildren(
  ArticoliRouteChildren,
)

interface KitRouteChildren {
  KitIdRoute: typeof KitIdRoute
}

const KitRouteChildren: KitRouteChildren = {
  KitIdRoute: KitIdRoute,
}

const KitRouteWithChildren = KitRoute._addFileChildren(KitRouteChildren)

interface PreventiviRouteChildren {
  PreventiviIdRoute: typeof PreventiviIdRoute
}

const PreventiviRouteChildren: PreventiviRouteChildren = {
  PreventiviIdRoute: PreventiviIdRoute,
}

const PreventiviRouteWithChildren = PreventiviRoute._addFileChildren(
  PreventiviRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticoliRoute: ArticoliRouteWithChildren,
  ClientiRoute: ClientiRoute,
  KitRoute: KitRouteWithChildren,
  ListiniRoute: ListiniRoute,
  LoginRoute: LoginRoute,
  PreventiviRoute: PreventiviRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UtentiRoute: UtentiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
